### ISSUE TITLE
Not preventing Wandering Trader spawns

### ISSUE THREAD

**Issue by rckymtnrfc** [Tfarcenim/NoSoliciting#1]
Created this after seeing the thread in the comments.  I created a new instance with Forge 31.2.36, No Soliciting 1.1 and JEI 6.0.2.12.  This is in single player, fyi but it was also not working on our current server.  "Chunk Range" = 2 in the config.

Here is the image of the sign.  
https://imgur.com/QnXxBDX

**Comment by Tfarcenim** [comment]
Finally, someone provided an easily reproducible case so I could fix it.
